name: Quality gate
on:
  push:

permissions:
  contents: read
  packages: read

env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: make lint
      - run: make typecheck
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: make test
  e2e:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: make test.e2e
  build:
    needs:
      - test
      - e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat .npmrc.template | sed -e "s/_VALUE_/$NODE_AUTH_TOKEN/" > .npmrc
      - run: make container.build;
